debug:
  loglevel: debug
window:
  width: 800
  height: 600
  title: Example
physics:
  gravity: 3
  pixelsPerMeter: 20
  airFrictionFactor: 0.02
  plateFrictionFactor: 0.5
  jumpAbility: 2
  jumpColdDownTime: 0.3
textures:
  - id: unknown
    path: ./texture/unknown.png
    alpha: true
  - id: BackgroundSprite
    path: ./texture/background.png
    alpha: true
  - id: PlayerSprite
    path: ./texture/player.png
    alpha: true
  - id: PlateSprite
    path: ./texture/plate.png
    alpha: true
  - id: BulletSprite
    path: ./texture/bullet.png
    alpha: true
states:
  MainMenu:
    objects:
      - name: background
        spriteId: BackgroundSprite
        width: 800
        height: 600
        zindex: -100
        type: gameObject
      - name: playButton
        posx: 300
        posy: 290
        width: 200
        height: 20
        type: staticObject
        onClickEvent: switchStateToGamePlay
  GamePlay:
    objects:
      - name: background
        spriteId: BackgroundSprite
        width: 800
        height: 600
        zindex: -100
        type: gameObject
      - name: player1
        spriteId: PlayerSprite
        posx: 100
        posy: -100
        width: 20
        height: 32
        type: rigidObject
        colorR: 1.0
        colorG: 0.8
        colorB: 0.8
        fireColdDownTime: 0.1
      - name: player2
        spriteId: PlayerSprite
        posx: 300
        posy: -100
        width: 20
        height: 32
        type: rigidObject
        colorR: 0.8
        colorG: 1.0
        colorB: 0.8
        fireColdDownTime: 0.5
      - name: player3
        spriteId: PlayerSprite
        posx: 500
        posy: -100
        width: 20
        height: 32
        type: rigidObject
        colorR: 0.8
        colorG: 0.8
        colorB: 1.0
        fireColdDownTime: 0.3
      - name: player4
        spriteId: PlayerSprite
        posx: 600
        posy: -100
        width: 20
        height: 32
        type: rigidObject
        colorR: 0.9
        colorG: 0.9
        colorB: 0.8
        fireColdDownTime: 0.8
      - name: plate1
        spriteId: PlateSprite
        posx: 100
        posy: 500
        width: 300
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: plate2
        spriteId: PlateSprite
        posx: 400
        posy: 450
        width: 300
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: plate3
        spriteId: PlateSprite
        posx: 250
        posy: 390
        width: 250
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: plate4
        spriteId: PlateSprite
        posx: 300
        posy: 250
        width: 170
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: plate5
        spriteId: PlateSprite
        posx: 450
        posy: 325
        width: 250
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: plate6
        spriteId: PlateSprite
        posx: 100
        posy: 325
        width: 250
        height: 25
        type: physicsFixedObject
        mess: 100
        zindex: -10
      - name: exitButton
        posx: 100
        posy: 100
        width: 20
        height: 20
        type: staticObject
        onClickEvent: switchStateToMainMenu
      - name: BulletPrototype
        spriteId: BulletSprite
        posx: -100
        posy: -100
        width: 36
        height: 3
        type: bulletObject
    keyMap:
      - key: w
        action: player1MoveUp
      - key: s
        action: player1MoveDown
      - key: a
        action: player1MoveLeft
      - key: d
        action: player1MoveRight
      - key: lshift
        action: player1Fire
      - key: up
        action: player2MoveUp
      - key: down
        action: player2MoveDown
      - key: left
        action: player2MoveLeft
      - key: right
        action: player2MoveRight
      - key: rctrl
        action: player2Fire
      - key: i
        action: player3MoveUp
      - key: k
        action: player3MoveDown
      - key: j
        action: player3MoveLeft
      - key: l
        action: player3MoveRight
      - key: ;
        action: player3Fire
      - key: num8
        action: player4MoveUp
      - key: num2
        action: player4MoveDown
      - key: num4
        action: player4MoveLeft
      - key: num6
        action: player4MoveRight
      - key: numenter
        action: player4Fire