debug:
  loglevel: debug
window:
  width: 800
  height: 600
  title: Example
textures:
  - id: unknown
    path: ./texture/unknown.png
    alpha: true
  - id: BackgroundSprite
    path: ./texture/background.png
    alpha: true
states:
  MainMenu:
    objects:
      - name: background
        spriteId: BackgroundSprite
        width: 800
        height: 600
        zindex: -100
        type: gameObject
      - name: playButton
        posx: 300
        posy: 290
        width: 200
        height: 20
        type: staticObject
        onClickEvent: switchStateToGamePlay
  GamePlay:
    objects:
      - name: background
        spriteId: BackgroundSprite
        width: 800
        height: 600
        zindex: -100
        type: gameObject
      - name: player1
        posx: 400
        posy: 300
        width: 20
        height: 20
        type: gameObject
      - name: exitButton
        posx: 100
        posy: 100
        width: 20
        height: 20
        type: staticObject
        onClickEvent: switchStateToMainMenu
    keyMap:
      - key: up
        action: player1MoveUp
      - key: down
        action: player1MoveDown
      - key: left
        action: player1MoveLeft
      - key: right
        action: player1MoveRight